import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'app.dart';
import 'core/services/notification_service.dart';
import 'core/services/sample_data_service.dart';
import 'core/services/analytics_service.dart';
import 'core/config/firebase_config.dart';

// Fallback: Try to import firebase_options.dart if .env is not available
// This allows the app to work with hardcoded config during development
// but production should use .env file
try {
  import 'firebase_options.dart' show DefaultFirebaseOptions;
} catch (_) {
  // firebase_options.dart not available, will use .env instead
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Load environment variables from .env file
  try {
    await dotenv.load(fileName: '.env');
    debugPrint('Environment variables loaded from .env');
  } catch (e) {
    debugPrint('Warning: Could not load .env file: $e');
    debugPrint('Falling back to firebase_options.dart if available');
  }
  
  // Initialize Firebase
  try {
    // Priority 1: Try to use secure environment variables from .env
    try {
      SecureFirebaseOptions.validate();
      await Firebase.initializeApp(
        options: SecureFirebaseOptions.currentPlatform,
      );
      debugPrint('Firebase initialized successfully from environment variables');
    } catch (envError) {
      // Priority 2: Fallback to firebase_options.dart (if available)
      try {
        // This will work if firebase_options.dart exists (generated by flutterfire configure)
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
        debugPrint('Firebase initialized from firebase_options.dart (fallback)');
        debugPrint('⚠️ WARNING: Using hardcoded Firebase config. Consider using .env for production!');
      } catch (_) {
        // Priority 3: Try without options (may work if google-services.json is present)
        await Firebase.initializeApp();
        debugPrint('Firebase initialized (fallback mode - using platform config files)');
      }
    }
  } catch (e) {
    // Firebase might not be configured, continue without it
    debugPrint('Firebase initialization error: $e');
    debugPrint('Note: Set up Firebase using .env file or run "flutterfire configure"');
  }
  
  // Initialize sample data (badges, sample questions)
  try {
    final sampleDataService = SampleDataService();
    await sampleDataService.initializeSampleData();
  } catch (e) {
    debugPrint('Sample data initialization error: $e');
  }
  
  // Initialize analytics service
  try {
    await AnalyticsService().initialize();
  } catch (e) {
    debugPrint('Analytics initialization error: $e');
  }
  
  // Initialize notification service
  final notificationService = NotificationService();
  await notificationService.initialize();
  
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}
